language: r

sudo: required

env:
  - WARNINGS_ARE_ERRORS=false
  
r_binary_packages:
  - phangorn

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'