# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

sudo: required

env:
  - WARNINGS_ARE_ERRORS=false
  
r_binary_packages:
  - phangorn

notifications:
  email:
    on_success: change
    on_failure: change
